services:
  trino:
    env_file: "./trino.env"
    hostname: trino_test
    ports:
      #- "9080:8080"
      - "9043:8443"
    image: "trinodb/trino:472"
    container_name: trino_db
    networks:
     - network_test
    restart: unless-stopped
    volumes:
      - ./etc:/etc/trino
    extra_hosts:
        - "host.docker.internal:host-gateway"
networks:
  network_test:
    name: network_test
    external: true
